// var a=10;
// var b="20";
// console.log(a+b);//output is 1020;
// var a=9;
// var b="5";
// console.log(a-b);
// //output is 4 and as well as is bug;
// var a="java";
// var b="script";
// console.log(a+b);
// //output  is javascript;
// var a="";
// var b="";
// console.log(a+b);
// output is nothing;
// var a=" ";
// var b=0;
// console.log(a+b);
// output is 0;

// var a="satish";
// var b= "nehu";
// console.log(a-b);
// output is NaN  nan full form not a number;
console.log(true+true);
